name: device takeout 
description: Keep track of devices
title: "test"
body:
- type: markdown
  attributes:
    value: "Bugs are the worst!"
- type: textarea
  attributes:
    label: "What's wrong?"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report.
